# Generated by Django 5.1 on 2024-12-02 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(error_messages={'unqiue': 'Author with this email address already exists'}, max_length=126, unique=True, verbose_name='author email address')),
                ('username', models.CharField(error_messages={'unique': 'Author with this username already exists'}, max_length=126, primary_key=True, serialize=False, unique=True, verbose_name='username of the author')),
                ('full_name', models.CharField(blank=True, max_length=126, null=True, verbose_name='name of user')),
                ('verified_user', models.BooleanField(default=False, verbose_name='email verified')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='blog id')),
                ('title', models.TextField(max_length=250, verbose_name='title of the blog')),
                ('date_of_publish', models.DateTimeField(auto_now_add=True, verbose_name='date of publish')),
                ('blog_content', models.TextField(max_length=25000, verbose_name='blog content')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author of the blog')),
            ],
        ),
    ]
