# Generated by Django 5.1 on 2024-12-02 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='full_name',
            new_name='name',
        ),
    ]
